services:
  
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    networks:
      - mariadb_wordpress
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
  
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    depends_on:
      - mariadb
    networks:
      - mariadb_wordpress
      - wordpress_nginx
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: on-failure
    depends_on:
      - wordpress
    networks:
      - wordpress_nginx
    env_file:
      - .env
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html 

volumes:
  mariadb_data:
    name: mariadb_data
    driver_opts:
      type: none
      device: /home/jaiveca-/data/mariadb
      o: bind
  wordpress_data:
    name: wordpress_data
    driver_opts:
      type: none
      device: /home/jaiveca-/data/wordpress
      o: bind  

networks:
  mariadb_wordpress:
    driver: bridge
  wordpress_nginx:
    driver: bridge
  