services: 
  wordpress:
    build:
      context: ./wordpress  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Optional: specify the Dockerfile name
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
  wordpress_data: